### ISSUE TITLE
unread count per a chat 

### ISSUE THREAD

**Issue by kotya341** [sendbird/SendBird-Android#61]
Hey guys, we are working on android task to create a chat list with a badge of unread count,
right now  what do we do to achieve this connect to the chat -> get as channel.unreadMessageCount
I understand that this is not optimal solution and we want to improve this.
I know that you have a public API method for this
GET https://api-{application_id}.sendbird.com/v3/group_channels/{channel_url}/messages/unread_count
is it possible to get the same result, but via android sdk

**Comment by AlexPrestonSB** [comment]
Hey @kotya341 I responded to you in the slack channel, will close this for now!
