### ISSUE TITLE
Fetch most recent messages on resume

### ISSUE THREAD

**Issue by AgiMaulana** [sendbird/SendBird-Android#65]
When app GroupChatFragment paused and there are new messages, fetch the most recent messages on resume automatically instead of by dragging it down.

`
        if (mMessageCollection != null && mMessageCollectionHandler != null) {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    mMessageCollection.fetch(MessageCollection.Direction.NEXT, null);
                }
            }, 1000);
        }
`

**Comment by janna-sendbird** [comment]
Hi, @AgiMaulana! Thank you for your feedback. We will consider this request when building the next release of this sample.
